"""Backfill Honcho email memory from FirmVault Activity Log email files.

This is a safe first phase for the local-Honcho email architecture: it imports
case emails already accepted into FirmVault, so it does not broaden Gmail scope
or ingest raw attachments/PDFs.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Iterable

import yaml

from plugins.memory.honcho.email_ingest import EmailMessage, HonchoEmailIngestor, IngestResult


def _parse_frontmatter_mapping(fm_text: str) -> dict:
    try:
        data = yaml.safe_load(fm_text) or {}
        return data if isinstance(data, dict) else {}
    except yaml.YAMLError:
        # Activity Log frontmatter is generated by agents and sometimes contains
        # raw email headers that are not valid YAML scalars, e.g.
        # to: "NAME" <email@example.com>. Fall back to a tolerant key/value parse.
        data = {}
        for raw in fm_text.splitlines():
            if not raw.strip() or raw.lstrip().startswith("#") or ":" not in raw:
                continue
            key, value = raw.split(":", 1)
            data[key.strip()] = value.strip()
        return data


def _split_frontmatter(text: str) -> tuple[dict, str] | None:
    if not text.startswith("---\n"):
        return None
    try:
        _, fm_text, body = text.split("---", 2)
    except ValueError:
        return None
    data = _parse_frontmatter_mapping(fm_text)
    return data, body.lstrip("\n")


def _extract_full_email_body(markdown_body: str) -> str:
    marker = "## Full email body"
    if marker not in markdown_body:
        return markdown_body.strip()
    return markdown_body.split(marker, 1)[1].strip()


def _as_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v) for v in value]
    return [str(value)]


def parse_activity_log_email(path: Path) -> EmailMessage | None:
    """Parse a FirmVault Activity Log email markdown file into EmailMessage."""

    text = path.read_text(errors="replace")
    split = _split_frontmatter(text)
    if not split:
        return None
    metadata, body = split
    if metadata.get("type") != "email":
        return None

    message_id = metadata.get("message_id") or metadata.get("gmail_message_id")
    thread_id = metadata.get("thread_id") or metadata.get("gmail_thread_id")
    if not message_id or not thread_id:
        return None

    return EmailMessage(
        gmail_message_id=str(message_id),
        gmail_thread_id=str(thread_id),
        from_header=str(metadata.get("from") or "unknown"),
        to_headers=_as_list(metadata.get("to")),
        subject=str(metadata.get("subject") or ""),
        date=str(metadata.get("date") or metadata.get("saved_at") or ""),
        body=_extract_full_email_body(body),
        labels=[],
        firmvault_path=str(path),
    )


def iter_case_email_logs(firmvault_cases_root: Path) -> Iterable[tuple[str, EmailMessage]]:
    """Yield (case_slug, EmailMessage) for email logs under FirmVault/cases."""

    for case_dir in sorted(firmvault_cases_root.iterdir()):
        if not case_dir.is_dir() or case_dir.name.startswith("_"):
            continue
        activity_dir = case_dir / "Activity Log"
        if not activity_dir.exists():
            continue
        for path in sorted(activity_dir.rglob("*.md")):
            email = parse_activity_log_email(path)
            if email:
                yield case_dir.name, email


def backfill_firmvault_emails(
    firmvault_cases_root: Path,
    *,
    ingestor: HonchoEmailIngestor | None = None,
    execute: bool = False,
) -> list[IngestResult]:
    """Backfill accepted FirmVault email logs into per-case Honcho workspaces.

    Dry-run by default: returns planned per-case/thread counts without writing.
    """

    grouped: dict[tuple[str, str], list[EmailMessage]] = defaultdict(list)
    for case_slug, email in iter_case_email_logs(firmvault_cases_root):
        grouped[(case_slug, email.gmail_thread_id)].append(email)

    results: list[IngestResult] = []
    writer = ingestor or HonchoEmailIngestor()
    for (case_slug, thread_id), messages in sorted(grouped.items()):
        if execute:
            results.append(writer.ingest_case_thread(case_slug, messages))
        else:
            from plugins.memory.honcho.email_ingest import case_workspace_id, session_id_for_thread

            results.append(
                IngestResult(
                    workspace_id=case_workspace_id(case_slug),
                    session_id=session_id_for_thread(thread_id),
                    seen=len(messages),
                    written=0,
                    skipped_existing=0,
                )
            )
    return results
